import Head from "next/head";
import Layout from "@/src/Layout";
import CategoriesList from "@/src/components/categoriesList/CategoriesList";

export default function Categorie() {
    return (
      <>
        <Head>
          <title>Ilprodottochecerchi.it</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favi.ico" />
        </Head>
        <Layout>
          <div>
        <CategoriesList/>
          </div>
        </Layout>
      </>
    );
  }
  