import Head from "next/head";
import styles from "@/styles/chiSiamo.module.scss";
import Layout from "@/src/Layout";
import { GiTeamIdea, GiTechnoHeart, GiOffshorePlatform } from "react-icons/gi";

export default function ChiSiamo() {
  return (
    <>
      <Head>
        <title>Ilprodottochecerchi.it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <Layout>
        <div className={styles.ChiSiamo}>
          <h2>
            Benvenuto su <span>ilprodottochecerchi.it</span>!
          </h2>
          <div className={styles.cards}>
            <div className={styles.card}>
              <GiTeamIdea className={styles.icon} />
              <p className={styles.text}>
                Siamo un team appassionato e dedicato di esperti nel settore
                dell'e-commerce. La nostra missione è semplice: fornirti una
                piattaforma intuitiva e conveniente per trovare i migliori
                prodotti che stai cercando, con un semplice clic che ti
                indirizza ad Amazon per l'acquisto.
              </p>
            </div>
            <div className={styles.card}>
              <GiOffshorePlatform className={styles.icon} />
              <p className={styles.text}>
                La nostra piattaforma è stata progettata per offrirti
                un'esperienza user-friendly e una navigazione fluida. Siamo
                consapevoli che il tuo tempo è prezioso, quindi ci impegniamo a
                presentarti solo le migliori offerte e promozioni disponibili su
                Amazon. Siamo partner affiliati di Amazon, il che significa che
                quando fai clic su uno dei prodotti che ti interessa e completi
                un acquisto su Amazon, riceviamo una piccola commissione. Questo
                ci consente di mantenere ilprodottochecerchi.it attivo e
                continuare a fornirti un servizio di qualità senza costi
                aggiuntivi per te.
              </p>
            </div>
            <div className={styles.card}>
              <GiTechnoHeart className={styles.icon} />
              <p className={styles.text}>
                Crediamo fermamente nella potenza della tecnologia e
                nell'accessibilità dei prodotti di qualità. Vogliamo
                semplificare il tuo processo di ricerca e acquisto, mettendo a
                tua disposizione una vasta selezione di articoli di tendenza e
                di alta qualità. Siamo costantemente alla ricerca di nuovi
                prodotti interessanti e innovativi per arricchire la tua
                esperienza di shopping online.
              </p>
            </div>
          </div>
          <p className={styles.regrets}>
            Grazie per aver scelto ilprodottochecerchi.it! Siamo grati per la
            tua fiducia in noi e ci impegniamo a offrirti sempre il meglio.
            Speriamo di diventare il tuo punto di riferimento per la scoperta di
            prodotti unici, i più recenti gadget e tutto ciò che soddisfa le tue
            esigenze e passioni. Se hai suggerimenti, domande o desideri
            condividi ti preghiamo di contattarci. <br />{" "}
            <span>
              Il team di <span>ilprodottochecerchi.it</span>
            </span>
          </p>
        </div>
      </Layout>
    </>
  );
}
