import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import { useState } from "react";
import { products } from "../src/mock/data";

// Layout
import Layout from "@/src/Layout";

// components
import Hero from "@/src/components/hero";
import CardList from "@/src/components/cardList";

export default function Home() {
  const [data, setData] = useState(products);

  return (
    <>
      <Head>
        <title>Ilprodottochecerchi.it</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <Hero />
          <CardList data={data} />
        </main>
      </Layout>
    </>
  );
}
